# Site settings
title: HUANG QING BLOG
SEOTitle: 黄庆的博客 | HUANG QING BLOG
header-img: img/post-bg-desk.jpg
email: hqdaoyidao@163.com
description: "天行健，君子以自强不息。地势坤，君子以厚德载物。"
keyword: "HUANG QING, HUANG QING Blog, 黄庆的博客, Front-End"
url: "http://huang-qing.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/huang-qing/huang-qing.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-huangqing-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username: huang-qing
# zhihu_username: huang-qing
github_username: huang-qing
# facebook_username: huang-qing
jianshu_username: a5f4cd1641eb
# twitter_username: huang-qing



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# gem plugins
plugins:
  - jekyll-feed
  - jekyll-paginate


# 评论系统


# Analytics settings
# Baidu Analytics
#ba_track_id: ''

# Google Analytics
#ga_track_id: ''            # Format: UA-xxxxxx-xx
#ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "简书",
        href: "http://www.jianshu.com/u/a5f4cd1641eb"
    },{
        title: "知乎",
        href: "https://www.zhihu.com/"
    },{
        title: "花瓣",
        href: "http://huaban.com/"
    },{
        title: "30 days of hiit",
        href: "https://darebee.com/programs/30-days-of-hiit.html?showall=&start=2"
    },{
        title: "163",
        href: "http://mail.163.com/"
    },{
        title: "图灵",
        href: "http://www.ituring.com.cn/book"
    },{
        title: "MDN Web Docs",
        href: "https://developer.mozilla.org/zh-CN/"
    },{
        title: "Google Developer",
        href: "https://developers.google.cn/"
    },{
        title: "W3",
        href: "https://www.w3.org/"
    },{
        title: "JSON",
        href: "http://www.json.org/"
    },{
        title: "Cordova",
        href: "http://cordova.apache.org/"
    },{
        title: "Android Developer",
        href: "https://developer.android.com/index.html"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    },{
        title: "雪球",
        href: "https://xueqiu.com/"
    },{
        title: "格隆汇",
        href: "http://www.guuzhang.com/"
    },{
        title: "TypeScript",
        href: "https://www.tslang.cn/"
    },{
        title: "C#",
        href: "https://docs.microsoft.com/zh-cn/dotnet/csharp/"
    },{
        title: "JavaScript(ES5 ES6)",
        href: "https://www.javascript.com/"
    },{
        title: "TypeScript",
        href: "https://www.typescriptlang.org/index.html"
    },{
        title: "HTML5",
        href: "https://developer.mozilla.org/zh-CN/docs/Web/Guide/HTML/HTML5"
    },{
        title: "JSON",
        href: "http://www.json.org/"
    },{
        title: "CSS3",
        href: "https://developer.mozilla.org/zh-CN/docs/Web/CSS"
    },{
        title: "Markdown",
        href: "http://www.markdown.cn/"
    },{
        title: "Visual Studio 2017",
        href: "https://www.visualstudio.com/zh-hans/vs/"
    },{
        title: "Visual Studio Code",
        href: "https://code.visualstudio.com/"
    },{
        title: "Visual Source Safe(VSS)",
        href: "https://msdn.microsoft.com/zh-cn/library/ms181038"
    },{
        title: "Team Foundation Server(TFS)",
        href: "https://www.visualstudio.com/zh-cn/news/releasenotes/tfs2017-relnotes"
    },{
        title: "Git",
        href: "https://git-scm.com/"
    },{
        title: "GitHub",
        href: "https://github.com/"
    },{
        title: "Google Chrome",
        href: "https://developers.google.com/web/tools/chrome-devtools/"
    },{
        title: "Fiddler",
        href: "http://www.telerik.com/fiddler"
    },{
        title: "VMware",
        href: "https://www.vmware.com/products/workstation.html"
    },{
        title: "Genymotion",
        href: "https://www.genymotion.com/"
    },{
        title: "ASP.NET Web Forms",
        href: "https://www.asp.net/web-forms"
    },{
        title: "ASP.NET MVC",
        href: "https://www.asp.net/mvc"
    },{
        title: "Bootstrap",
        href: "http://www.bootcss.com/"
    },{
        title: "Angular",
        href: "https://angular.cn/"
    },{
        title: "Ionic",
        href: "http://ionicframework.com/docs/"
    },{
        title: "Cordova",
        href: "http://cordova.apache.org/docs/en/latest/"
    },{
        title: "jQuery",
        href: "http://jquery.com/"
    },{
        title: "Raphaël",
        href: "http://dmitrybaranovskiy.github.io/raphael/"
    },{
        title: "Moment.js",
        href: "http://momentjs.cn/"
    },{
        title: "Echarts",
        href: "http://echarts.baidu.com/index.html"
    },{
        title: "Charts.js",
        href: "http://www.chartjs.org/"
    },{
        title: "RxJS",
        href: "http://cn.rx.js.org/"
    },{
        title: "three.js",
        href: "https://threejs.org/"
    },{
        title: "Node.js",
        href: "https://nodejs.org/zh-cn/"
    },{
        title: "jekyll",
        href: "http://jekyllcn.com/"
    },{
        title: "NPM",
        href: "https://www.npmjs.com/"
    },{
        title: "淘宝 NPM 镜像",
        href: "http://npm.taobao.org/"
    },{
        title: "Gulp",
        href: "http://www.gulpjs.com.cn/"
    },{
        title: "webpack",
        href: "https://webpack.js.org/"
    },{
        title: "ngrok",
        href: "https://ngrok.com/"
    },{
        title: "rubyinstaller",
        href: "https://rubyinstaller.org/"
    },{
        title: "github desktop",
        href: "https://desktop.github.com/"
    }
]

# Technology Stack
technology_stack: [
{
    classify: "Programming Language",
    content: [{
        title: "C#",
        href: "https://docs.microsoft.com/zh-cn/dotnet/csharp/"
    },{
        title: "JavaScript(ES5 ES6)",
        href: "https://www.javascript.com/"
    },{
        title: "TypeScript",
        href: "https://www.typescriptlang.org/index.html"
    },{
        title: "HTML5",
        href: "https://developer.mozilla.org/zh-CN/docs/Web/Guide/HTML/HTML5"
    },{
        title: "JSON",
        href: "http://www.json.org/"
    },{
        title: "CSS3",
        href: "https://developer.mozilla.org/zh-CN/docs/Web/CSS"
    },{
        title: "Markdown",
        href: "http://www.markdown.cn/"
    }]
},
{
    classify: "IDE(Integrated Development Environment)",
    content: [{
        title: "Visual Studio 2017",
        href: "https://www.visualstudio.com/zh-hans/vs/"
    },{
        title: "Visual Studio Code",
        href: "https://code.visualstudio.com/"
    }]
},
{
    classify: "Distributed Version Control System",
    content: [{
        title: "Visual Source Safe(VSS)",
        href: "https://msdn.microsoft.com/zh-cn/library/ms181038"
    },{
        title: "Team Foundation Server(TFS)",
        href: "https://www.visualstudio.com/zh-cn/news/releasenotes/tfs2017-relnotes"
    },{
        title: "Git",
        href: "https://git-scm.com/"
    },{
        title: "GitHub",
        href: "https://github.com/"
    }]
},
{
    classify: "Debugger",
    content: [{
        title: "Google Chrome",
        href: "https://developers.google.com/web/tools/chrome-devtools/"
    },{
        title: "Fiddler",
        href: "http://www.telerik.com/fiddler"
    },{
        title: "VMware",
        href: "https://www.vmware.com/products/workstation.html"
    },{
        title: "Genymotion",
        href: "https://www.genymotion.com/"
    }]
},
{
    classify: "Framework",
    content: [{
        title: "ASP.NET Web Forms",
        href: "https://www.asp.net/web-forms"
    },{
        title: "ASP.NET MVC",
        href: "https://www.asp.net/mvc"
    },{
        title: "Bootstrap",
        href: "http://www.bootcss.com/"
    },{
        title: "Angular",
        href: "https://angular.cn/"
    },{
        title: "Ionic",
        href: "http://ionicframework.com/docs/"
    },{
        title: "Cordova",
        href: "http://cordova.apache.org/docs/en/latest/"
    }]
},
{
    classify: "Library",
    content: [{
        title: "jQuery",
        href: "http://jquery.com/"
    },{
        title: "Raphaël",
        href: "http://dmitrybaranovskiy.github.io/raphael/"
    },{
        title: "Moment.js",
        href: "http://momentjs.cn/"
    },{
        title: "Echarts",
        href: "http://echarts.baidu.com/index.html"
    },{
        title: "Charts.js",
        href: "http://www.chartjs.org/"
    },{
        title: "RxJS",
        href: "http://cn.rx.js.org/"
    },{
        title: "three.js",
        href: "https://threejs.org/"
    }]
},
{
    classify: "Toolkit",
    content: [{
        title: "Node.js",
        href: "https://nodejs.org/zh-cn/"
    },{
        title: "NPM",
        href: "https://www.npmjs.com/"
    },{
        title: "淘宝 NPM 镜像",
        href: "http://npm.taobao.org/"
    },{
        title: "Gulp",
        href: "http://www.gulpjs.com.cn/"
    },{
        title: "webpack",
        href: "https://webpack.js.org/"
    },{
        title: "ngrok",
        href: "https://ngrok.com/"
    }]
}]